baseURL = ""
title = "StatistiCon"
languageCode = "en-us"
theme = "gohugo-theme-ananke"


# Allow section list pages (needed for /news/)
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark]
  [markup.goldmark.parser]
    autoHeadingIDType = "github"
    
[params.social]
instagram = "https://www.instagram.com/statisticon/"
whatsapp = "https://chat.whatsapp.com/CuiRUZvYS1Z7LqKV7f4lTu"